import AboutUs from '../../../component/ui/AboutUs';
import HotelBreadCrumb from '../../../component/ui/HotelBreadCrumb'

export const metadata = {
    title: "About Us",
    description: "Generated by create next app",
  };

const About = () => {
    const base = 'Home'
  return (
    <>
        <div style={{margin:"20px 0"}}>
        <HotelBreadCrumb  items={[
          {
            label: `${base}`,
            link: '/',
          },
          {
            label: 'About Us',
            link: '/about',
            
          },
        ]} style={{paddingLeft:"20px "}}/>
        <AboutUs/>
    </div>
    </>
  )
}

export default About