


export const metadata = {
  title: 'Hotel Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    
     
     
     <>
     {children}
     </>
     
      
  )
}
