'use client'
import "./globals.css";
import Providers from '../lib/Providers';

// export const metadata = {
//   title: "Hotel Booking",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Providers suppressHydrationWarning={true}>
      <html lang="en" >
        <body>{children}</body>
      </html>
    </Providers>
  );
}

