import Head from 'next/head'
import './globals.css';
import UiHeader from '../component/ui/UiHeader';
import UiFooter from '../component/ui/UiFooter';


export const metadata = {
  title: 'Hotel Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
    <Head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    </Head>
      <body>
      <UiHeader/> 
      {children}
      <UiFooter/> 
      </body>
    </html>
  )
}
