import RegisterPage from '../../../component/LogIn/RegisterPage'
import CommonBanner from '../../../component/ui/CommonBanner';

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

const Register = () => {
  const bannerLinks = [
    {text: "SignUp"}
  ]
  return (
    <>
    <CommonBanner title="Register" links={bannerLinks}/>
        <div style={{margin: '20px 0'}}>
        <RegisterPage/>
        </div>
    </>
  )
}

export default Register