import RegisterPage from '../../../component/LogIn/RegisterPage'

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

const Register = () => {
  return (
    <>
        <RegisterPage/>
    </>
  )
}

export default Register