import LoginPage from '../../../component/LogIn/LoginPage';
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <>
      <LoginPage/>
    </>
  )
}

export default Login